name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check changed files
        id: check-files
        run: |
          # Get the list of changed files
          FILES=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files --jq '.[].filename')
          echo "Changed files: $FILES"

          # Check if only allowed files are changed
          ALLOWED=true
          for file in $FILES; do
            if [[ "$file" == .github/workflows/*.yml ]] || [[ "$file" == .github/workflows/*.yaml ]] || [[ "$file" == "requirements.txt" ]]; then
              echo "Allowed file: $file"
            else
              echo "Non-allowed file: $file"
              ALLOWED=false
              break
            fi
          done

          echo "allowed=$ALLOWED" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for status checks
        if: steps.check-files.outputs.allowed == 'true'
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-checks
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Ruff
          ref: ${{ github.event.pull_request.head.sha }}
          timeoutSeconds: 600

      - name: Auto-merge Dependabot PR
        if: steps.check-files.outputs.allowed == 'true' && steps.wait-for-checks.outputs.conclusion == 'success'
        run: |
          gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
